services:
  - type: web
    name: ultrapay-moov
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
    autoDeploy: true